# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module MyAnimeListApi
  class Anime < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :alternative_versions

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :character_anime

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :classification

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :end_date

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :episodes

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :favorited_count

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :genres

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :image_url

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :listed_anime_id

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :manga_adaptations

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :members_count

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :members_score

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :other_titles

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :parent_story

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :popularity_rank

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :prequels

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :rank

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :score

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :sequels

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :side_stories

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :spin_offs

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :start_date

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :summaries

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :synopsis

    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :tags

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :watched_episodes

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :watched_status

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["alternative_versions"] = "alternative_versions"
        @hash["character_anime"] = "character_anime"
        @hash["classification"] = "classification"
        @hash["end_date"] = "end_date"
        @hash["episodes"] = "episodes"
        @hash["favorited_count"] = "favorited_count"
        @hash["genres"] = "genres"
        @hash["id"] = "id"
        @hash["image_url"] = "image_url"
        @hash["listed_anime_id"] = "listed_anime_id"
        @hash["manga_adaptations"] = "manga_adaptations"
        @hash["members_count"] = "members_count"
        @hash["members_score"] = "members_score"
        @hash["other_titles"] = "other_titles"
        @hash["parent_story"] = "parent_story"
        @hash["popularity_rank"] = "popularity_rank"
        @hash["prequels"] = "prequels"
        @hash["rank"] = "rank"
        @hash["score"] = "score"
        @hash["sequels"] = "sequels"
        @hash["side_stories"] = "side_stories"
        @hash["spin_offs"] = "spin_offs"
        @hash["start_date"] = "start_date"
        @hash["status"] = "status"
        @hash["summaries"] = "summaries"
        @hash["synopsis"] = "synopsis"
        @hash["tags"] = "tags"
        @hash["title"] = "title"
        @hash["type"] = "type"
        @hash["watched_episodes"] = "watched_episodes"
        @hash["watched_status"] = "watched_status"
      end
      @hash
    end

    def initialize(alternative_versions = nil,
                   character_anime = nil,
                   classification = nil,
                   end_date = nil,
                   episodes = nil,
                   favorited_count = nil,
                   genres = nil,
                   id = nil,
                   image_url = nil,
                   listed_anime_id = nil,
                   manga_adaptations = nil,
                   members_count = nil,
                   members_score = nil,
                   other_titles = nil,
                   parent_story = nil,
                   popularity_rank = nil,
                   prequels = nil,
                   rank = nil,
                   score = nil,
                   sequels = nil,
                   side_stories = nil,
                   spin_offs = nil,
                   start_date = nil,
                   status = nil,
                   summaries = nil,
                   synopsis = nil,
                   tags = nil,
                   title = nil,
                   type = nil,
                   watched_episodes = nil,
                   watched_status = nil)
      @alternative_versions = alternative_versions
      @character_anime = character_anime
      @classification = classification
      @end_date = end_date
      @episodes = episodes
      @favorited_count = favorited_count
      @genres = genres
      @id = id
      @image_url = image_url
      @listed_anime_id = listed_anime_id
      @manga_adaptations = manga_adaptations
      @members_count = members_count
      @members_score = members_score
      @other_titles = other_titles
      @parent_story = parent_story
      @popularity_rank = popularity_rank
      @prequels = prequels
      @rank = rank
      @score = score
      @sequels = sequels
      @side_stories = side_stories
      @spin_offs = spin_offs
      @start_date = start_date
      @status = status
      @summaries = summaries
      @synopsis = synopsis
      @tags = tags
      @title = title
      @type = type
      @watched_episodes = watched_episodes
      @watched_status = watched_status
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        alternative_versions = hash["alternative_versions"]
        character_anime = hash["character_anime"]
        classification = hash["classification"]
        end_date = hash["end_date"]
        episodes = hash["episodes"]
        favorited_count = hash["favorited_count"]
        genres = hash["genres"]
        id = hash["id"]
        image_url = hash["image_url"]
        listed_anime_id = hash["listed_anime_id"]
        manga_adaptations = hash["manga_adaptations"]
        members_count = hash["members_count"]
        members_score = hash["members_score"]
        other_titles = hash["other_titles"]
        parent_story = hash["parent_story"]
        popularity_rank = hash["popularity_rank"]
        prequels = hash["prequels"]
        rank = hash["rank"]
        score = hash["score"]
        sequels = hash["sequels"]
        side_stories = hash["side_stories"]
        spin_offs = hash["spin_offs"]
        start_date = hash["start_date"]
        status = hash["status"]
        summaries = hash["summaries"]
        synopsis = hash["synopsis"]
        tags = hash["tags"]
        title = hash["title"]
        type = hash["type"]
        watched_episodes = hash["watched_episodes"]
        watched_status = hash["watched_status"]

        # Create object from extracted values
        Anime.new(alternative_versions,
                  character_anime,
                  classification,
                  end_date,
                  episodes,
                  favorited_count,
                  genres,
                  id,
                  image_url,
                  listed_anime_id,
                  manga_adaptations,
                  members_count,
                  members_score,
                  other_titles,
                  parent_story,
                  popularity_rank,
                  prequels,
                  rank,
                  score,
                  sequels,
                  side_stories,
                  spin_offs,
                  start_date,
                  status,
                  summaries,
                  synopsis,
                  tags,
                  title,
                  type,
                  watched_episodes,
                  watched_status)
      end
    end
  end
end
