# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module MyAnimeListApi

  class Configuration
    # The base Uri for API calls
    @base_uri = 'http://v2-mal-api.herokuapp.com'

    # The attribute accessors for public properties
    class << self
      attr_accessor :base_uri
    end
 
  end
end
