# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module MyAnimeListApi
  class MyAnimeListAPIClient
    # Singleton access to anime controller
    # @return [AnimeController] Returns the controller instance
    def anime
      AnimeController.instance
    end

    # Singleton access to manga controller
    # @return [MangaController] Returns the controller instance
    def manga
      MangaController.instance
    end

    # Singleton access to user controller
    # @return [UserController] Returns the controller instance
    def user
      UserController.instance
    end

  end
end
