# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'my_anime_list_api/api_helper.rb'
require_relative 'my_anime_list_api/my_anime_list_api_client.rb'

# Http
require_relative 'my_anime_list_api/http/http_call_back.rb'
require_relative 'my_anime_list_api/http/http_client.rb'
require_relative 'my_anime_list_api/http/http_method_enum.rb'
require_relative 'my_anime_list_api/http/http_request.rb'
require_relative 'my_anime_list_api/http/http_response.rb'
require_relative 'my_anime_list_api/http/http_context.rb'
require_relative 'my_anime_list_api/http/faraday_client.rb'

# Models
require_relative 'my_anime_list_api/models/base_model.rb'
require_relative 'my_anime_list_api/models/retrieve_an_anime_response.rb'
require_relative 'my_anime_list_api/models/anime.rb'
require_relative 'my_anime_list_api/models/search_for_an_anime_response.rb'

# Exceptions
require_relative 'my_anime_list_api/exceptions/api_exception.rb'

require_relative 'my_anime_list_api/configuration.rb'

# Controllers
require_relative 'my_anime_list_api/controllers/base_controller.rb'
require_relative 'my_anime_list_api/controllers/anime_controller.rb'
require_relative 'my_anime_list_api/controllers/manga_controller.rb'
require_relative 'my_anime_list_api/controllers/user_controller.rb'
